version: "3"

services:
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - ./database:/data/db
  # mongo-seed:
  #   build: ./Books.Infra/Seed
  #   links:
  #     - mongodb
  api:
    build: .
    ports:
      - "5000:80"
    depends_on:
      - mongodb
    volumes:
      - ./:/app
